repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args:
          - --py36-plus
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        name: trailing-whitespace
      - id: end-of-file-fixer
        name: end-of-file-fixer
      - id: double-quote-string-fixer
        name: double-quote-string-fixer
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.4.0
    hooks:
      - id: add-trailing-comma
        name: add-trailing-comma
        args:
          - --py36-plus
  - repo: https://github.com/asottile/setup-cfg-fmt
    rev: v2.2.0
    hooks:
      - id: setup-cfg-fmt
        args:
          - --max-py-version=3.10
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        name: flake8-package
        additional_dependencies:
          - flake8-print
          - flake8-implicit-str-concat
        files: ^mkdocs_mdpo_plugin/
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        name: flake8-tests
        additional_dependencies:
          - flake8-print
          - flake8-implicit-str-concat
        files: ^tests/
  - repo: https://github.com/PyCQA/isort
    rev: 5.11.4
    hooks:
      - id: isort
        args:
          - --filter-files
        files: \.py$
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.28.0
    hooks:
      - id: yamllint
        files: .+\.(yml|yaml)
        args:
          - -c
          - .yamllint
  - repo: https://github.com/mondeja/pre-commit-po-hooks
    rev: v1.7.3
    hooks:
      - id: untranslated-messages
        exclude: file-excluded-from-translations\.md\.po
      - id: obsolete-messages
      - id: fuzzy-messages
      - id: remove-metadata
  - repo: https://github.com/mondeja/repo-stream
    rev: v1.3.1
    hooks:
      - id: repo-stream
        args:
          - -config=https://github.com/mondeja/repo-stream-config
          - -updater=upstream
  - repo: https://github.com/mondeja/pre-commit-hooks
    rev: v1.8.0
    hooks:
      - id: dev-extras-required
      - id: root-editorconfig-required
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 2.6.2
    hooks:
      - id: editorconfig-checker
