site_name: mkdocs-mdpo-plugin Mkdocs theme example
site_url: https://mkdocs-mdpo.ga
docs_dir: docs/src

nav:
  - Home: index.md

theme:
  name: readthedocs

plugins:
  - search
  - mdpo:
      languages:
        - en
        - es
        - fr
      cross_language_search: false
      locale_dir: ../locale
