site_name: mkdocs-mdpo-plugin Material example
site_url: https://mkdocs-mdpo.ga
docs_dir: docs/src
edit_uri: tree/master/docs/src
repo_url: https://github.com/mondeja/mkdocs-mdpo-plugin

theme:
  name: material
  language: en

nav:
  - Home: index.md
  - Foo: foo.md

plugins:
  - search
  - mdpo:
      cross_language_search: false
      locale_dir: ../locale

extra:
  alternate:
    - name: English
      lang: en
    - name: Español
      link: es
      lang: es
    - name: Français
      link: fr
      lang: fr
