site_name: mkdocs-mdpo-plugin 'min_translated_messages' example
site_url: https://mkdocs-mdpo.ga
docs_dir: docs/src

nav:
  - Home: index.md
  - File excluded from translations: file-excluded-from-translations.md

plugins:
  - search
  - mdpo:
      languages:
        - en
        - es
        - fr
      cross_language_search: false
      locale_dir: ../locale
      min_translated_messages: 55%
